# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# TODO: rails 4.2 doesn't support 'shared', but rails 5.1 does
#   ... so need to update this is we upgrade.
shared: &shared
  redis_url: <%= ENV['REDIS_URL'] %>
  matterhorn_url: <%= ENV['MATTERHORN_URL'] %>
  matterhorn_client_media_path: <%= ENV['MATTERHORN_CLIENT_MEDIA_PATH'] %>
  matterhorn_server_media_path: <%= ENV['MATTERHORN_SERVER_MEDIA_PATH'] %>
  lti_servers:
<% ENV['LTI_SERVERS'].to_s.split.each do |server| %>
    - <%= server %>
<% end %>
  lti_auth_key: <%= ENV['LTI_AUTH_KEY'] %>
  lti_auth_secret: <%= ENV['LTI_AUTH_SECRET'] %>
  email_comments: <%= ENV['EMAIL_COMMENTS'] || 'avalon-comments@example.edu' %>
  email_notification: <%= ENV['EMAIL_NOTIFICATION'] ||
                          'avalon-notifications@example.edu'%>
  email_support: <%= ENV['EMAIL_SUPPORT'] || 'avalon-support@example.edu'%>
  email_errors: <%= ENV['EMAIL_ERRORS'] || 'avalon-errors@example.edu' %>

development:
  <<: *shared
  secret_key_base: 8268df0c1b5843bec6d0e6e1095b187766ff6a8f9c1edd4360588d357253fac09c95aebc715f25cb3ecfdf45cfb2da6c1c033149e93a363f3808da67b0b8ab09
  fcrepo_url: <%= ENV['FCREPO_URL'] || 'http://localhost:8984/fcrepo/rest' %>
  fcrepo_user: fedoraAdmin
  fcrepo_password: fedoraAdmin
  fcrepo_base_path: /dev
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  matterhorn_url: <%= ENV['MATTERHORN_URL'] ||
                      "http://matterhorn_system_account:CHANGE_ME@localhost:8080/" %>
  matterhorn_client_media_path: <%= ENV['MATTERHORN_CLIENT_MEDIA_PATH'] ||
                                    File.join(Rails.root, 'masterfiles') %>
  matterhorn_server_media_path: <%= ENV['MATTERHORN_SERVER_MEDIA_PATH'] ||
                                    '/masterfiles' %>
  rollbar_token: ''

test:
  <<: *shared
  secret_key_base: f589c05f948f5760c95e5c60fa0fb325a9fa7e8c9ba8190d22b8ff868927215dd4e5252227245dd26b4e98c9441ce5ef34a14ea25b2170191cb3f5ddad6c5755
  fcrepo_url: <%= ENV['FCREPO_URL'] || 'http://localhost:8984/fcrepo/rest' %>
  fcrepo_user: fedoraAdmin
  fcrepo_password: fedoraAdmin
  fcrepo_base_path: /test
  redis_url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>

  matterhorn_url: <%= ENV['MATTERHORN_URL'] ||
                      "http://matterhorn_system_account:CHANGE_ME@localhost:8080/" %>
  matterhorn_client_media_path: <%= ENV['MATTERHORN_CLIENT_MEDIA_PATH'] ||
                                    File.join(Rails.root, 'masterfiles') %>
  matterhorn_server_media_path: <%= ENV['MATTERHORN_SERVER_MEDIA_PATH'] ||
                                    '/masterfiles' %>
  rollbar_token: ''

# Do not keep production secrets in the repository,
# instead read values from the environment.

uat:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  database_url: <%= ENV['DATABASE_URL'] %>
  fcrepo_user: <%= ENV['FCREPO_USER'] %>
  fcrepo_password: <%= ENV['FCREPO_PASSWORD'] %>
  fcrepo_url: <%= ENV['FCREPO_URL'] %>
  fcrepo_base_path: /uat
  solr_url: <%= ENV['SOLR_URL'] %>
  rollbar_token: ''

staging:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  database_url: <%= ENV['DATABASE_URL'] %>
  fcrepo_user: <%= ENV['FCREPO_USER'] %>
  fcrepo_password: <%= ENV['FCREPO_PASSWORD'] %>
  fcrepo_url: <%= ENV['FCREPO_URL'] %>
  fcrepo_base_path: /staging
  solr_url: <%= ENV['SOLR_URL'] %>
  rollbar_token: ''

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  database_url: <%= ENV['DATABASE_URL'] %>
  fcrepo_user: <%= ENV['FCREPO_USER'] %>
  fcrepo_password: <%= ENV['FCREPO_PASSWORD'] %>
  fcrepo_url: <%= ENV['FCREPO_URL'] %>
  fcrepo_base_path: /prod
  solr_url: <%= ENV['SOLR_URL'] %>
  rollbar_token: <%= ENV['ROLLBAR_TOKEN'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
