name: 'ERA A+V' # used in page titles
domain:
  host: localhost
  port: 80
  protocol: http
dropbox:
  path: /srv/avalon/dropbox
  upload_uri: sftp://avalon.example.edu
encoding:
  engine_adapter: matterhorn
matterhorn:
  root: 'http://localhost:8080/'
  baseApplication: 'avalon'
  cleanup_log: 'log/cleanup_jobs.log'
mediainfo:
  path: '/usr/bin/mediainfo'
ffmpeg:
  path: '/usr/local/bin/ffmpeg'
email:
  mailer: :smtp
  comments: <%= Rails.application.secrets.email_comments %>
  notification: <%= Rails.application.secrets.email_notification %>
  support: <%= Rails.application.secrets.email_support %>
  errors: <%= Rails.application.secrets.email_errors %>
solr:
  configset: avalon
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: avalon
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:
zookeeper:
  connection_str: "localhost:9983/configs"
streaming:
  server: :generic
  stream_token_ttl: 20 #minutes
  content_path: '/srv/avalon/content'
  rtmp_base: 'rtmp://localhost/avalon'
  http_base: 'http://localhost:3000/streams'
  default_quality: 'auto'
redis:
  host: localhost
  port: 6379
groups:
  system_groups: [administrator, group_manager, manager]
master_file_management:
  strategy: 'none' #'delete', or 'move' (for move uncomment and configure next line)
  #path: '/path/to/move/to'
bib_retriever:
  protocol: sru
  url: http://zgate.example.edu:9000/exampledb
  query: rec.id='%s'
controlled_vocabulary:
  path: config/controlled_vocabulary.yml
encode_throttling:
  create_jobs_throttle_threshold: 2
  create_jobs_spacing: 5
  update_jobs_throttle_threshold: 3
  update_jobs_spacing: 10
auth:
  configuration:
<% if Rails.env.development? || Rails.env.test? %>
    - :name: Avalon Test Auth
      :provider: :identity
      :params:
        :fields:
        - :email
<% end %>
<% if Rails.application.secrets.lti_auth_key.present? %>
    - :name: Avalon LTI OAuth
      :provider: :lti
      :hidden: true
      :params:
        :oauth_credentials:
          <%= Rails.application.secrets.lti_auth_key %>: <%= Rails.application.secrets.lti_auth_secret %>
<% end %>
<% if Rails.env.staging? || Rails.env.production? %>
    - :name: Avalon Shibboleth OAuth
      :provider: :shibboleth
<% end %>
